openapi: 3.0.0
info:
  title: Gateway API
  version: 1.0.0
paths:
  /v1/users:
    post:
      summary: Creates a new user
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  rel:
                    type: object
                    properties:
                      self:
                        type: string
                        example: '/v1/users/foo'
        '400':
          description: Bad Request
        '409':
          description: Conflict
        '415':
          description: Unsupported Media Type
        '422':
          description: Unprocessable Entity

  /v1/users/{username}:
    get:
      summary: Gets user info
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  rel:
                    type: object
                    properties:
                      self:
                        type: string
                        example: '/v1/users/foo'
                      session:
                        type: string
                        example: '/v1/users/sessions/foo'
        '406':
          description: Not Acceptable

    patch:
      summary: Updates user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                password:
                  type: string
                session-token:
                  type: string
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  username:
                    type: string
                  rel:
                    type: object
                    properties:
                      self:
                        type: string
                        example: '/v1/users/foo'
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '415':
          description: Unsupported Media Type
        '422':
          description: Unprocessable Entity

    delete:
      summary: Deletes a user
      parameters:
        - name: username
          in: path
          required: true
          schema:
            type: string
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                session-token:
                  type: string
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '403':
          description: Forbidden
        '415':
          description: Unsupported Media Type
        '422':
          description: Unprocessable Entity

  /v1/users/sessions:
    post:
      summary: Starts a user session
      requestBody:
        required: true
        content:
          application/json:
            schema:
              type: object
              properties:
                username:
                  type: string
                password:
                  type: string
      responses:
        '201':
          description: Created
          content:
            application/json:
              schema:
                type: object
                properties:
                  session-token:
                    type: string
                  rel:
                    type: object
    delete:
      summary: Terminates session
      parameters:
        - in: path
          name: username
          required: true
          schema:
            type: string
        - in: header
          name: session-token
          required: true
          schema:
            type: string
      responses:
        '204':
          description: No Content
        '400':
          description: Bad Request
        '401':
          description: Unauthorized
        '415':
          description: Unsupported Media Type
        '422':
          description: Unprocessable Entity